# Resources:
# Money
# Food
# Corners (priesthood) (positive only!)
# Soldiers (positive only!)
available_buildings = {
    "Home": {'Name': "Home",
             'Resource Change': {'food': 2,
                                 'corners': 4},
             'Initial Cost': {},
             'Next': "Castle",
             'Build Key': None,
             'Min Corners': 4,
             'Frame': 1},

    "Castle": {'Name': "Castle",
               'Resource Change': {'food': -100,
                                   'money': -100},
               'Initial Cost': {'money': 5000},
               'Min Corners': 10,
               'Build Key': None,
               'Next': None,
               'Frame': 0},

    "Market": {'Name': "Market",
               'Resource Change': {'food': -5,
                                   'money': 3},
               'Initial Cost': {'food': 1},
               'Min Corners': 4,
               'Build Key': 'm',
               'Next': "Restaurant",
               'Frame': 4},

    "Restaurant": {'Name': "Restaurant",
                   'Resource Change': {'food': -5,
                                       'money': 15},
                   'Initial Cost': {'food': 30,
                                    'money': 20},
                   'Min Corners': 7,
                   'Build Key': None,
                   'Next': None,
                   'Frame': 0},

    "Farm": {'Name': "Farm",
             'Resource Change': {'food': 20},
             'Initial Cost': {'money': 2},
             'Min Corners': 4,
             'Build Key': 'f',
             'Next': "Factory",
             'Frame': 0},

    "Factory": {'Name': "Factory",
                'Resource Change': {'food': 100},
                'Initial Cost': {'money': 25},
                'Min Corners': 8,
                'Build Key': None,
                'Next': None,
                'Frame': 0},

    "School": {'Name': "School",
               'Resource Change': {'food': -1,
                                   'money': 0,
                                   'corners': 5},
               'Initial Cost': {'money': 5},
               'Min Corners': 4,
               'Build Key': 's',
               'Next': "Church",
               'Frame': 12},

    "Church": {'Name': "Church",
               'Resource Change': {'food': 0,
                                   'money': -2,
                                   'corners': 7},
               'Initial Cost': {'money': 50},
               'Min Corners': 6,
               'Build Key': None,
               'Next': "Hospital",
               'Frame': 0},

    "Hospital": {'Name': "Hospital",
                 'Resource Change': {'food': -1,
                                     'money': -2,
                                     'corners': 8},
                 'Initial Cost': {'money': 500},
                 'Min Corners': 7,
                 'Build Key': None,
                 'Next': "Priesthood",
                 'Frame': 12},

    "Priesthood": {'Name': "Priesthood",
                   'Resource Change': {'food': -1,
                                       'money': -15,
                                       'corners': 10},
                   'Initial Cost': {'money': 5000},
                   'Min Corners': 8,
                   'Build Key': None,
                   'Next': None,
                   'Frame': 0},

    "Pontoon": {'Name': "Pontoon",
                'Resource Change': {'food': 0,
                                    'money': 0,
                                    'corners': 6},
                'Initial Cost': {'money': 5},
                'Min Corners': 5,
                'Build Key': 'p',
                'Next': None,
                'Frame': 0},

    "Barracks": {'Name': "Barracks",
                 'Resource Change': {'food': -10,
                                     'money': -2,
                                     'corners': 4},
                 'Initial Cost': {'money': 25},
                 'Min Corners': 5,
                 'Build Key': 'b',
                 'Next': None,
                 'Frame': 0},

}


building_messages = {
    'on_existing_building': "sorry, you might be mighty, but you can't build where there already is stone laid",
    'build_success': "A new building was built",
    'no_resource': "Missing resources: ",
    'upgrade_success': "Building was successfully upgraded",
    'not_on_building': "Before upgrading, you have to first build!",
    'building_on_water': "You can't build this on water!",
    'no_upgrade_available': "This building is already awesome, no need to make it better?!"}
